export const DEPARTMENTS = [
    { id: 'Surgery', label: 'Surgery | ศัลยกรรมทั่วไป' },
    { id: 'Orthopedics', label: 'Orthopedics | ศัลยกรรมกระดูกและข้อ' },
    { id: 'Urology', label: 'Urology | ศัลยกรรมระบบทางเดินปัสสาวะ' },
    { id: 'ENT', label: 'ENT | ศัลยกรรม โสต ศอ นาสิก' },
    { id: 'OBGYN', label: 'Obstetrics-Gynecology | สูติ-นรีเวช' },
    { id: 'Ophthalmology', label: 'Ophthalmology | จักษุ' },
    { id: 'Maxillofacial', label: 'Maxillofacial | ศัลยกรรมขากรรไกร' },
];

export const WARDS = [
    "หอผู้ป่วยอายุรกรรมชาย",
    "หอผู้ป่วยอายุรกรรมหญิง",
    "หอผู้ป่วยจิตเวช",
    "หอผู้ป่วยพิเศษรวมน้ำใจ",
    "หอผู้ป่วยศัลยกรรมชาย",
    "หอผู้ป่วยศัลยกรรมหญิง",
    "หอผู้ป่วยหนักอายุรกรรมชั้น 1(ICU-MED_1)",
    "หอผู้ป่วยหนักอายุรกรรมชั้น 2(ICU-MED_2)",
    "หอผู้ป่วยกระดูกและข้อ",
    "หอผู้ป่วยพิเศษอายุรกรรมชั้น4",
    "หอผู้ป่วยพิเศษศัลยกรรมชั้น4",
    "หอผู้ป่วยกุมารเวช",
    "หอผู้ป่วยอภิบาลสงฆ์",
    "หอผู้ป่วยโสต ศอ นาสิก",
    "หอผู้ป่วยพิเศษสูติ-นรีเวช ชั้น5",
    "หอผู้ป่วยพิเศษสูติ-นรีเวช ชั้น4",
    "หอผู้ป่วยพิเศษกุมารเวช",
    "หอผู้ป่วยศัลยกรรมระบบประสาทและสมอง",
    "หอผู้ป่วยหนักกุมารเวช(NICU)",
    "หอผู้ป่วยสูติ-นรีเวช (PP)",
    "หอผู้ป่วยหนักรวม(ICU_รวม)",
    "ห้องอุบัติเหตุฉุกเฉิน",
    "ห้องผ่าตัด",
    "วิสัญญีพยาบาล",
    "ห้องคลอด"
];

export const NURSES = [
    "อรุณี", "ศิวดาติ์", "กัญญณัช", "ชัญญาภัค", "สุนทรี", "พิศมัย", "เทวัญ", "กันต์พงษ์",
    "ปนัฏฐา", "สุจิตรา", "ชัยยงค์", "สุภาวัลย์", "จันทจร", "วรรณิภา", "ณัฐพงษ์", "ตะวัน",
    "ปวีณา", "นิฤมล", "ปริญญา", "สยุมพร", "สุรสิทธ์", "บุศรินทร์", "ศิริกัญญา", "นราวัตน์",
    "บัณฑิตา", "วรรณวิสา", "ชลดา", "วรีสา", "สุภกิจ",
];

export const DOCTOR_DEPARTMENT_MAPPING: Record<string, string> = {
    // Surgery
    "นพ.สุริยา คุณาชน": "Surgery",

    // Auto-map others if known, otherwise generic fallback logic might be needed
    // or we just rely on the user selecting it if not found.
};

export const DIAGNOSIS_BY_DEPT: Record<string, string[]> = {
    "Surgery": [
        "Acute appendicitis",
        "Acute cholecystitis",
        "Choledocholithiasis",
        "Biliary obstruction",
        "Inguinal hernia",
        "Ventral (incisional) hernia",
        "Hemorrhoids",
        "Colorectal cancer",
        "Rectal cancer",
        "Gastrointestinal bleeding",
        "Small bowel obstruction",
        "Large bowel obstruction",
        "Perforated peptic ulcer",
        "Acute pancreatitis (surgical consult)",
        "Breast cancer",
        "Benign breast tumor (fibroadenoma)",
        "Soft-tissue abscess",
        "Cellulitis with fluctuance",
        "Diabetic foot infection",
        "Critical limb ischemia",
        "Peritonitis",
        "Intestinal ischemia (suspected)",
        "Gastric cancer",
        "Gastric outlet obstruction",
        "Dysphagia with feeding difficulty",
        "Perianal abscess",
        "Anal fissure (refractory)",
        "Anal fistula",
        "Bowel perforation",
        "Post-operative intra-abdominal collection",
        "Acute abdomen (undifferentiated)",
        "Appendiceal mass/abscess",
        "Diverticulitis with complication",
        "Adhesive small bowel obstruction",
        "Toxic megacolon",
        "Mesenteric ischemia",
        "Esophageal perforation",
        "Achalasia (surgical)",
        "Thyroglossal duct cyst",
        "Lipoma (trunk/extremity)",
        "Soft-tissue sarcoma",
        "Splenic rupture",
        "Pancreatic pseudocyst",
        "Bile leak after cholecystectomy",
        "Stoma complication",
        "Short bowel syndrome",
        "Malnutrition requiring enteral access",
        "Necrotizing soft tissue infection",
        "Fournier gangrene",
    ],
    "Urology": [
        "Benign prostatic hyperplasia",
        "Bladder tumor",
        "Kidney stone",
        "Ureteric stone",
        "Bladder stone",
        "Hematuria (evaluation)",
        "Prostate cancer",
        "Renal cell carcinoma",
        "Obstructive uropathy",
        "Hydronephrosis",
        "Pyonephrosis",
        "Acute urinary retention",
        "Complicated urinary tract infection",
        "Acute pyelonephritis",
        "Urethral stricture",
        "Neurogenic bladder",
        "Testicular tumor",
        "Epididymo-orchitis (complicated)",
        "Phimosis",
        "Refractory balanitis",
        "Vesicoureteral reflux",
        "Renal colic",
        "Non-functioning kidney",
        "Staghorn calculus",
        "Upper tract urothelial carcinoma",
        "Carcinoma in situ of bladder",
        "Ureteropelvic junction obstruction",
        "Perineal abscess",
        "Post-operative hematuria",
        "Iatrogenic ureteral injury",
        "Bladder neck contracture",
        "Stress urinary incontinence",
        "Refractory urge incontinence",
        "Urethral diverticulum",
        "Ureteral stricture",
        "Retroperitoneal fibrosis (obstructive)",
        "Renal angiomyolipoma (surgical)",
        "Testicular torsion (post-fixation care)",
        "Hydrocele",
        "Varicocele",
        "Spermatocele",
        "Penile fracture",
        "Peyronie disease (surgical)",
        "Penile carcinoma",
        "Neurogenic detrusor overactivity (procedural)",
        "Chronic catheter dependency",
        "Bladder perforation (iatrogenic)",
        "Urachal remnant lesion",
        "Recurrent prostatitis (procedural)",
    ],
    "ENT": [
        "Chronic tonsillitis",
        "Adenoid hypertrophy",
        "Chronic rhinosinusitis",
        "Nasal polyposis",
        "Deviated nasal septum",
        "Otitis media with effusion",
        "Tympanic membrane perforation",
        "Epistaxis",
        "Benign vocal cord lesion",
        "Laryngeal cancer",
        "OSA due to adenotonsillar hypertrophy",
        "Thyroid nodule",
        "Thyroid cancer",
        "Parotid gland tumor",
        "Primary hyperparathyroidism",
        "Neck mass",
        "Nasolacrimal duct obstruction",
        "Foreign body in ear",
        "Foreign body in nose",
        "Foreign body in esophagus",
        "Peritonsillar abscess",
        "Retropharyngeal abscess",
        "Chronic otitis media",
        "Cholesteatoma",
        "Sinonasal inverted papilloma",
        "Hoarseness due to vocal cord lesion",
        "Subglottic stenosis",
        "Tracheal stenosis",
        "Recurrent epistaxis",
        "Sinonasal mucocele",
        "Vocal cord paralysis",
        "Supraglottic lesion",
        "Oropharyngeal cancer",
        "Hypopharyngeal cancer",
        "Mandibular osteomyelitis",
        "Sialolithiasis",
        "Chronic sialadenitis",
        "Branchial cleft cyst",
        "Thyroglossal duct cyst",
        "Head-and-neck hemangioma/vascular malformation",
        "Nasal valve collapse",
        "Eustachian tube dysfunction",
        "Otosclerosis",
        "Menière disease (procedural)",
        "Skull base CSF leak",
        "Facial nerve schwannoma",
        "Parapharyngeal space tumor",
        "Zenker diverticulum",
    ],
    "OBGYN": [
        "Cesarean delivery",
        "Incomplete abortion",
        "Missed abortion",
        "High-grade cervical intraepithelial neoplasia",
        "Uterine fibroids",
        "Ovarian cyst",
        "Adnexal mass",
        "Ectopic pregnancy",
        "Ovarian torsion",
        "Ovarian cancer",
        "Endometriosis (surgical management)",
        "Pelvic adhesive disease",
        "Complicated pelvic inflammatory disease",
        "Endometrial polyp",
        "Abnormal uterine bleeding due to fibroids",
        "Postpartum hemorrhage (surgical control)",
        "Perineal tear (repair)",
        "Vulvovaginal hematoma",
        "Bartholin cyst",
        "Bartholin abscess",
        "Infertility due to tubal factor (surgical)",
        "Chronic pelvic pain (surgical evaluation)",
        "Ovarian endometrioma",
        "Ruptured ectopic pregnancy",
        "Uterine prolapse",
        "Cystocele",
        "Rectocele",
        "Iatrogenic uterine perforation",
        "Acute abdomen in gynecology",
        "Ovarian hyperstimulation complication",
        "Adenomyosis (surgical)",
        "Cervical polyp",
        "Uterine septum",
        "Cesarean scar defect (isthmocele)",
        "Retained products of conception",
        "Placenta accreta spectrum",
        "Cervical incompetence",
        "Vulvar intraepithelial neoplasia",
        "Vulvar cyst/tumor (excision)",
        "Vaginal vault prolapse",
        "Stress urinary incontinence (urogynecologic)",
        "Vesicovaginal fistula",
        "Rectovaginal fistula",
        "Ovarian dermoid cyst",
        "Paraovarian cyst",
        "Broad ligament fibroid",
        "Tubo-ovarian abscess",
        "Hydrosalpinx",
        "Post-abortal sepsis",
    ],
    "Orthopedics": [
        "Intertrochanteric femur fracture",
        "Femoral neck fracture",
        "Subtrochanteric femur fracture",
        "Femoral shaft fracture",
        "Tibial shaft fracture",
        "Distal tibia (pilon) fracture",
        "Distal radius fracture",
        "Humeral shaft fracture",
        "Supracondylar humerus fracture",
        "Ankle fracture",
        "Clavicle fracture",
        "Olecranon fracture",
        "Patellar fracture",
        "Acetabular fracture",
        "Proximal humerus fracture",
        "Scaphoid fracture",
        "Knee osteoarthritis",
        "Hip osteoarthritis",
        "ACL tear",
        "Meniscal tear",
        "Rotator cuff tear",
        "Recurrent shoulder instability",
        "Lumbar disc herniation",
        "Cervical spondylosis with radiculopathy",
        "Thoracic vertebral compression fracture",
        "Carpal tunnel syndrome",
        "De Quervain tenosynovitis",
        "Trigger finger",
        "Ulnar neuropathy at elbow",
        "Achilles tendon rupture",
        "Plantar fasciitis (surgical)",
        "Hallux valgus",
        "Adult acquired flatfoot",
        "Charcot arthropathy (foot)",
        "Osteomyelitis (long bone)",
        "Symptomatic heterotopic ossification",
        "Benign bone tumor (excision)",
        "Bone metastasis (stabilization)",
        "Avascular necrosis of femoral head",
        "Nonunion fracture",
        "Malunion fracture",
        "Acute compartment syndrome of limb",
        "Tendon injury of hand",
        "Peripheral nerve laceration",
        "Prosthesis loosening (hip/knee)",
        "Periprosthetic joint infection",
        "Periprosthetic fracture",
        "Patellar tendon tear",
        "Quadriceps tendon tear",
        "Lateral epicondylitis (surgical)",
    ],
    "Ophthalmology": [
        "Age-related cataract",
        "Primary open-angle glaucoma",
        "Primary angle-closure glaucoma",
        "Pterygium",
        "Nasolacrimal duct obstruction",
        "Chalazion",
        "Hordeolum",
        "Endophthalmitis",
        "Globe rupture",
        "Eyelid laceration",
        "Conjunctival laceration",
        "Canalicular laceration",
        "Ptosis",
        "Dermatochalasis",
        "Entropion",
        "Ectropion",
        "Corneal ulcer",
        "Complicated corneal abrasion",
        "Traumatic hyphema",
        "Rhegmatogenous retinal detachment",
        "Epiretinal membrane",
        "Macular hole",
        "Diabetic vitreous hemorrhage",
        "Proliferative diabetic retinopathy (surgical)",
        "Thyroid eye disease (surgical)",
        "Orbital tumor",
        "Chronic dacryocystitis",
        "Trichiasis",
        "Symblepharon",
        "Severe dry eye with punctal stenosis",
        "Corneal dystrophy (keratoplasty)",
        "Keratoconus (CXL/keratoplasty)",
        "Traumatic cataract",
        "Pseudophakic bullous keratopathy",
        "Iris coloboma (repair)",
        "Dislocated intraocular lens",
        "Angle-recession glaucoma",
        "Neovascular glaucoma",
        "Uveitic cataract",
        "Pediatric cataract",
        "Congenital nasolacrimal duct obstruction",
        "Congenital ptosis",
        "Orbital cellulitis (surgical drainage)",
        "Canalicular stenosis",
        "Eyelid tumor",
        "Orbital dermoid cyst",
        "Retinal detachment with PVR",
        "Macular pucker",
        "Ocular surface squamous neoplasia",
        "Chemical ocular injury (surgical care)",
    ],
    "Maxillofacial": [
        "Nasal bone fracture",
        "Mandibular fracture",
        "Le Fort fracture",
        "Zygomaticomaxillary complex fracture",
        "Orbital floor fracture",
        "Panfacial fracture",
        "Post-traumatic malocclusion",
        "Facial laceration",
        "Facial soft-tissue loss",
        "Odontogenic cyst",
        "Impacted third molar",
        "Odontogenic tumor",
        "Oral cavity cancer",
        "Leukoplakia with dysplasia",
        "Mandibular osteomyelitis",
        "TMJ ankylosis",
        "TMJ internal derangement (surgical)",
        "Maxillary sinusitis of dental origin (surgical)",
        "Sialolithiasis",
        "Chronic sialadenitis",
        "Post-traumatic facial deformity",
        "Nonunion mandibular fracture",
        "Malunion facial fracture",
        "Oroantral fistula",
        "Oronasal fistula",
        "Trismus due to fibrosis",
        "Oral mucosal fibroma",
        "Mucocele of minor salivary gland",
        "Ranula",
        "Cleft alveolus (secondary)",
        "Alveolar ridge deficiency",
        "Mandibular defect after tumor resection",
        "Zygomatic arch fracture",
        "Frontal sinus fracture (anterior table)",
        "Orbital wall defect (post-trauma)",
        "Condylar process fracture",
        "Coronoid impingement",
        "Inferior alveolar/lingual nerve injury",
        "Parotid duct injury/stone",
        "Submandibular space infection",
        "Ludwig angina (surgical drainage)",
        "Hemifacial atrophy (reconstruction)",
        "Perioral scar contracture",
        "Upper lip oncologic defect",
        "Mandibular prognathism/retrognathism",
        "Maxillary hypoplasia",
        "Failed dental implant (removal/revision)",
        "Peri-implantitis (surgical)",
        "Osteoradionecrosis of jaw",
        "Facial nerve weakness sequelae (reanimation planning)",
    ],
};

export const OPERATIONS_BY_DEPT: Record<string, string[]> = {
    "Surgery": [
        "Appendectomy",
        "Laparoscopic Cholecystectomy (LC)",
        "Open Cholecystectomy (OC)",
        "Common Bile Duct Exploration",
        "Choledochoduodenostomy",
        "T-Tube Insertion with Cholangiogram",
        "Herniorrhaphy / Hernioplasty",
        "Hemorrhoidectomy",
        "Exploratory Laparotomy",
        "Endoscopic Retrograde Cholangiopancreatography",
        "Esophagogastroduodenoscopy",
        "Colonoscopy",
        "Incision and Drainage",
        "Debridement",
        "Wound Exploration and Suturing",
        "Low Anterior Resection",
        "Hartmann’s Procedure",
        "Colostomy (Creation/Revision)",
        "Ileostomy (Creation/Revision)",
        "End-to-End Anastomosis / Iliocecal Anastomosis",
        "Right Hemicolectomy",
        "Left Hemicolectomy",
        "Sigmoid Colectomy",
        "Subtotal Colectomy",
        "Small Bowel Resection",
        "Omentectomy",
        "Lysis of Adhesions",
        "Subtotal Gastrectomy",
        "Roux-en-Y Reconstruction",
        "Splenectomy",
        "Partial Hepatectomy",
        "Pancreatic Necrosectomy",
        "Distal Pancreatectomy",
        "Pancreaticoduodenectomy (Whipple)",
        "Anal Fistulotomy / Fistulectomy",
        "Lateral Internal Sphincterotomy",
        "Pilonidal Sinus Excision",
        "Lymph Node Biopsy",
        "Excision of Breast Mass",
        "Mastectomy / Modified Radical Mastectomy",
        "Gastrostomy",
        "Feeding Jejunostomy / Feeding Enterostomy",
        "Tracheostomy (Creation/Revision/Closure)",
        "Percutaneous Drainage (Intra-abdominal)",
        "Ray Amputation",
        "Transmetatarsal Amputation",
        "Below-Knee Amputation",
        "Above-Knee Amputation",
        "Proctoscopy / Rigid Sigmoidoscopy",
        "Vacuum-Assisted Wound Closure Application",
    ],
    "Urology": [
        "Transurethral Resection of the Prostate (TURP)",
        "Transurethral Resection of Bladder Tumor (TURBT)",
        "Percutaneous Nephrolithotomy (PCNL)",
        "Retrograde Intrarenal Surgery (RIRS)",
        "Ureteroscopy with Lithotripsy (URSL)",
        "Transurethral Lithotripsy (TUL)",
        "Double J Stent Insertion",
        "Double J Stent Removal",
        "Antegrade Double J Stent Placement",
        "Cystoscopy",
        "Flexible Cystoscopy",
        "TRUS-Guided Prostate Biopsy",
        "Simple/Radical Nephrectomy",
        "Radical Prostatectomy",
        "Radical Cystectomy with Ileal Conduit",
        "Partial Nephrectomy",
        "Pyeloplasty",
        "Ureterolithotomy",
        "Pyelolithotomy",
        "Cystolitholapaxy",
        "Urethroplasty",
        "Optical Internal Urethrotomy (OIU/DVIU)",
        "Urethral Dilatation",
        "Suprapubic Catheter Insertion",
        "Percutaneous Nephrostomy Insertion",
        "Nephrostomy Exchange/Removal",
        "Radical Orchidectomy",
        "Orchiopexy",
        "Varicocelectomy",
        "Hydrocelectomy",
        "Circumcision",
        "Vasectomy",
        "Scrotal Exploration and Drainage",
        "Hematuria Fulguration",
        "Bladder Biopsy and Fulguration",
        "Ureteral Reimplantation",
        "Boari Flap Ureteric Reconstruction",
        "Penile Prosthesis Implantation",
        "Meatotomy / Meatal Dilatation",
        "Penile Fracture Repair",
        "Retrograde Pyelography",
        "Antegrade Pyelography",
        "Ureteral Stent Exchange",
        "Nephrostogram",
        "Partial Cystectomy",
        "Bladder Augmentation",
        "Artificial Urinary Sphincter Implantation",
        "Testicular Prosthesis Insertion",
        "Epididymectomy",
        "Spermatocelectomy",
    ],
    "ENT": [
        "Tonsillectomy",
        "Adenoidectomy",
        "Adenotonsillectomy",
        "Functional Endoscopic Sinus Surgery (FESS)",
        "Septoplasty / Septectomy",
        "Inferior Turbinectomy / Turbinoplasty",
        "Nasal Polypectomy",
        "Myringotomy with Pressure Equalization Tube",
        "Tympanoplasty",
        "Mastoidectomy",
        "Ossiculoplasty",
        "Stapedectomy / Stapedotomy",
        "Direct Laryngoscopy with Biopsy",
        "Microlaryngoscopy",
        "Panendoscopy",
        "Tracheostomy (Creation/Revision/Closure)",
        "Parotidectomy",
        "Hemithyroidectomy / Total Thyroidectomy",
        "Parathyroidectomy",
        "Sistrunk’s Operation",
        "Endoscopic Dacryocystorhinostomy",
        "External Dacryocystorhinostomy",
        "Anterior Nasal Packing",
        "Nasal Cauterization for Epistaxis",
        "Endoscopic Maxillary Antrostomy",
        "Endoscopic Ethmoidectomy",
        "Septoplasty with Turbinate Reduction",
        "Rigid Esophagoscopy",
        "Bronchoscopy with Foreign Body Removal",
        "Balloon Sinuplasty",
        "Uvulopalatopharyngoplasty",
        "Selective/Modified Neck Dissection",
        "Partial/Total Laryngectomy",
        "Vocal Cord Injection / Microlaryngoscopic Excision",
        "Ear Toilet and Debridement",
        "Myringoplasty",
        "Tympanomastoidectomy",
        "Choanal Atresia Repair",
        "Septorhinoplasty",
        "Endoscopic Turbinate Coblation",
        "Epiglottoplasty",
        "Cricothyrotomy",
        "Scar Revision (Head & Neck)",
        "Submandibular Gland Excision",
        "Parotid Duct Stone Removal",
        "Thyroglossal Duct Cyst Excision",
        "Vocal Cord Medialization Thyroplasty",
        "Balloon Eustachian Tuboplasty",
        "Endoscopic Frontal Sinusotomy",
    ],
    "OBGYN": [
        "Cesarean Section",
        "Dilatation and Curettage",
        "Manual Vacuum Aspiration",
        "Loop Electrosurgical Excision Procedure (LEEP)",
        "Cervical Biopsy",
        "Cervical Polypectomy",
        "Myomectomy",
        "Total Abdominal Hysterectomy",
        "Subtotal Abdominal Hysterectomy",
        "Laparoscopic Hysterectomy",
        "Vaginal Hysterectomy",
        "Salpingo-Oophorectomy",
        "Bilateral Salpingo-Oophorectomy",
        "Ovarian Cystectomy",
        "Oophorectomy",
        "Salpingectomy",
        "Tubal Resection",
        "Laparoscopic Salpingostomy",
        "Diagnostic/Operative Laparoscopy",
        "Lysis of Adhesions",
        "Hysterotomy",
        "Hysteroscopic Polypectomy",
        "Hysteroscopic Myomectomy",
        "Hysteroscopic Adhesiolysis",
        "Endometrial Ablation",
        "Operative Laparoscopy for Endometriosis",
        "Uterine Artery Ligation for PPH",
        "Episiotomy and Perineal Repair",
        "Repair of 3rd/4th-Degree Perineal Tear",
        "Evacuation of Vulvovaginal Hematoma",
        "Marsupialization of Bartholin Cyst",
        "Cervical Cerclage",
        "Tubal Ligation",
        "Uterosacral Ligament Suspension",
        "Sacrospinous Fixation",
        "Sacrocolpopexy",
        "Anterior/Posterior Colporrhaphy",
        "Repair of Uterine Perforation",
        "Laparoscopic Myomectomy",
        "Ovarian Drilling",
        "Cystoscopy (Intra-op)",
        "Manual Removal of Placenta",
        "Postpartum Curettage",
        "Laparoscopic Oophoropexy",
        "Hysteroscopic Septum Resection",
        "Bartholin Gland Excision",
        "Perineorrhaphy",
        "Vulvar Lesion Excision",
        "Laparoscopic Management of Ectopic Pregnancy",
    ],
    "Orthopedics": [
        "Open Reduction and Internal Fixation (ORIF)",
        "Closed Reduction and Internal Fixation (CRIF)",
        "Closed Reduction",
        "Intramedullary Nailing (Interlocking Nail)",
        "Locking Compression Plate Fixation",
        "Tension Band Wiring",
        "Proximal Femoral Nail Antirotation (PFNA)",
        "External Fixation",
        "Implant Removal (Plate/Screw/Nail/K-wire)",
        "Total Knee Arthroplasty",
        "Total Hip Replacement",
        "Unicompartmental Knee Arthroplasty",
        "Revision Arthroplasty (Knee/Hip)",
        "Bipolar Hemiarthroplasty",
        "Achilles Tendon Repair",
        "Anterior Cruciate Ligament Reconstruction",
        "Medial Collateral Ligament Repair",
        "Arthroscopic Meniscectomy",
        "Meniscal Repair",
        "Rotator Cuff Repair",
        "Subacromial Decompression",
        "Bankart/Capsulolabral Repair",
        "SLAP Repair",
        "Ulnar Nerve Decompression at Elbow",
        "Carpal Tunnel Release",
        "Trigger Finger Release",
        "De Quervain Release",
        "Tendon Transfer / Tenolysis",
        "Distal Radius Volar Plating",
        "Hallux Valgus Correction",
        "Ankle Ligament Reconstruction (Broström)",
        "Ankle Arthrodesis",
        "Wrist Arthroscopy",
        "Elbow ORIF",
        "Patellar Tendon Repair",
        "Quadriceps Tendon Repair",
        "Laminectomy",
        "Microdiscectomy",
        "Transforaminal Lumbar Interbody Fusion",
        "Posterolateral Fusion",
        "Pedicle Screw Fixation",
        "Percutaneous Sacroiliac Screw Fixation",
        "Kyphoplasty / Vertebroplasty",
        "Correction Osteotomy with Plate Fixation",
        "Split-Thickness Skin Graft",
        "Fasciotomy",
        "Skeletal Traction",
        "Bone Biopsy",
        "Excision of Heterotopic Ossification",
        "Removal of External Fixator",
    ],
    "Ophthalmology": [
        "Phacoemulsification with Intraocular Lens",
        "Extracapsular Cataract Extraction with IOL",
        "Intracapsular Cataract Extraction with IOL",
        "Trabeculectomy",
        "Glaucoma Drainage Device Implantation",
        "Endoscopic Dacryocystorhinostomy",
        "External Dacryocystorhinostomy",
        "Pterygium Excision with Graft",
        "Incision and Curettage of Chalazion",
        "Anterior Vitrectomy",
        "Vitreous Tapping with Intravitreal Antibiotic Injection",
        "Evisceration",
        "Enucleation",
        "Exenteration",
        "Repair of Globe",
        "Repair of Eyelid Laceration",
        "Repair of Conjunctival Laceration",
        "Canaliculus Repair",
        "Levator Advancement for Ptosis",
        "Blepharoplasty",
        "Lateral Tarsal Strip",
        "Scleral Fixation Intraocular Lens",
        "Entropion Repair",
        "Ectropion Repair",
        "Temporary / Definitive Tarsorrhaphy",
        "Corneal Scraping and Culture",
        "Amniotic Membrane Transplantation",
        "Penetrating Keratoplasty",
        "Descemet’s Stripping Endothelial Keratoplasty",
        "Corneal Cross-Linking",
        "Scleral Buckling",
        "Pars Plana Vitrectomy",
        "Endolaser Photocoagulation",
        "Retinal Membrane Peeling",
        "Macular Hole Surgery",
        "Silicone Oil Injection / Removal",
        "Orbitotomy for Mass",
        "Dacryocystectomy",
        "Punctoplasty with Intubation",
        "Canaliculo-DCR",
        "Müller Muscle Conjunctival Resection",
        "Brow Ptosis Repair",
        "Ptosis Sling with Fascia Lata",
        "Enucleation with Implant",
        "Secondary Intraocular Lens Implantation",
        "Strabismus Surgery",
        "Conjunctival Autograft for Pterygium",
        "Symblepharon Release",
        "Orbital Decompression",
        "Eyelid Tumor Excision with Reconstruction",
    ],
    "Maxillofacial": [
        "Open Reduction and Internal Fixation of Facial Fracture",
        "Closed Reduction of Nasal Bone Fracture",
        "Closed Reduction of Le Fort Fracture",
        "Arch Bar / Maxillomandibular Fixation",
        "Mini Plate and Screw Fixation",
        "Removal of Mini Plate and Screw",
        "Debridement of Facial Wound",
        "Repair and Suturing of Facial Wound",
        "Enucleation of Mandibular Cyst",
        "Surgical Extraction of Impacted Third Molar",
        "Alveoloplasty",
        "Incision and Drainage of Odontogenic Abscess",
        "Excision of Oral Lesion",
        "Wide Excision of Oral–Maxillofacial Lesion",
        "Incisional Biopsy (Oral–Maxillofacial)",
        "Open Reduction of Mandibular Fracture",
        "Open Reduction of ZMC Fracture",
        "Orbital Floor Reconstruction",
        "Le Fort I Osteotomy",
        "Bilateral Sagittal Split Osteotomy",
        "Reconstruction with Local Flap",
        "Skin Graft (Facial/Oral)",
        "Bone Graft (Mandible/Maxilla)",
        "TMJ Ankylosis Release",
        "TMJ Arthroplasty",
        "Maxillary Sinus Lift",
        "Closure of Oroantral Fistula",
        "Closure of Oronasal Fistula",
        "Facial Scar Revision",
        "Septorhinoplasty (OMFS scope)",
        "Submandibular Gland Excision",
        "Parotid Duct Stone Removal",
        "Sialolithotomy",
        "Ranula Excision",
        "Mucocele Excision",
        "Fibroma Excision (Oral Mucosa)",
        "Cleft Lip Repair (Secondary)",
        "Cleft Palate Repair (Secondary)",
        "Alveolar Bone Graft",
        "Free Fibula Flap Mandibular Reconstruction",
        "Distraction Osteogenesis (Mandible/Maxilla)",
        "Genioplasty",
        "Orbital Wall Reconstruction with Mesh",
        "Condylectomy",
        "Coronoidectomy",
        "Lingual/Inferior Alveolar Nerve Repair",
        "Dental Implant Placement (Hospital Setting)",
        "Removal of Foreign Body (Face/Oral Cavity)",
        "Drainage of Submandibular Space Infection",
        "Tracheostomy (Airway for OMFS)",
    ],
};

// ========== STAFF FOR WORK SCHEDULE (ตารางปฏิบัติงานประจำวัน) ==========

// พนักงานผู้ช่วย (Assistants) - ใช้สำหรับ "เวร Key" ด้วย
export const STAFF_ASSISTANTS = [
    "ดวงจันทร์",
    "สุภาวดี",
    "ณิชามล",
    "ไพลิน",
    "สุทธิดา",
    "วรรณนิศา",
    "พิมพ์วิภา",
];

// คนงาน (Workers)
export const STAFF_WORKERS = [
    "นาที",
    "อนุพันธ์",
    "กฤษณพงษ์",
    "นัฐพงษ์",
    "ศราวุธ",
    "รัตนพล",
    "อนุพงษ์",
];
