-- Add Admin User to SurgiTrack
-- Run this AFTER setup_database.sql

USE surgitrack;

-- Insert admin user with bcrypt hashed password
-- Password: admin123
-- Hash generated by: bcrypt.hashpw(b'admin123', bcrypt.gensalt())
INSERT INTO users (username, password_hash, full_name, role, is_active)
VALUES (
    'admin',
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.6HlXfWJXpNqDCe',
    'System Administrator',
    'admin',
    TRUE
)
ON DUPLICATE KEY UPDATE 
    password_hash = '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.6HlXfWJXpNqDCe',
    is_active = TRUE;

-- Also add a nurse user for testing
-- Password: nurse123
INSERT INTO users (username, password_hash, full_name, role, is_active)
VALUES (
    'nurse',
    '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    'Test Nurse',
    'nurse',
    TRUE
)
ON DUPLICATE KEY UPDATE 
    password_hash = '$2b$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    is_active = TRUE;

-- Verify
SELECT id, username, full_name, role, is_active FROM users;
